Material/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from rest_framework import routers
# from example.api.views import PersonaViewSet

# router = routers.DefaultRouter()
# router.register(r'persona', PersonaViewSet)

urlpatterns = [
    # url(r'^api/', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('example.urls')),
    url(r'^api', include('example.api.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/api/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
  url(r'^', views.PersonaListAPIView.as_view()),
]

example/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.LoginList.as_view(), name="index"),
    url(r'^comment/(?P<persona_id>[\w]+)/', views.comments),
    url(r'^noti/$', views.noti, name="noti"),
    url(r'^chat/$', views.chat, name="chat"),
    url(r'^user/$', views.prefile, name="profile"),
    url(r'^vcall/$', views.vcall, name="vcall"),
    url(r'^help/$', views.helpme, name="help"),
    url(r'^register/$', views.register, name="register"),
]

example/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

class Persona(models.Model):
	nombre = models.CharField(max_length=300)
	correo = models.EmailField()
	edad = models.IntegerField()
	image = CloudinaryField("photos")

	def __unicode__(self):
  		return self.nombre
	
	def __str__(self):
  		return self.nombre

class Comment(models.Model):
	persona = models.ForeignKey(User, related_query_name='persona')
	ref_persona = models.ForeignKey(Persona, related_name='ref_persona', blank=True, null=True)
	text = models.TextField( blank=True, null=True)
	image = models.ImageField(upload_to="comments/", blank=True, null=True)

	def __str__(self):
		person = self.persona
		ref_person = self.ref_persona
		text = self.text
		image = self.image

		return '%s had commented %s %s in %s' % (person, text, image, ref_person)






		

example/api/views.py
import django_filters
from rest_framework import serializers, viewsets, permissions
from rest_framework.generics import ListAPIView, ListCreateAPIView
from .serializers import PersonaSerializer
from ..models import Persona

# class PersonaFilter(django_filters.rest_framework.FilterSet):
#   class Meta:
#     model = Persona
#     fields = ['nombre', 'edad', 'correo']

class PersonaListAPIView(ListCreateAPIView):
  queryset = Persona.objects.all()
  serializer_class = PersonaSerializer
  filter_backends = (django_filters.rest_framework.DjangoFilterBackend,)
  filter_fields = ['nombre', 'edad', 'correo']
  # permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

example/views.py
import cloudinary

from django.shortcuts import render, get_list_or_404, redirect
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView

from .models import Persona, Comment
from .form import FormPersona, FormComment
from cloudinary.forms import cl_init_js_callbacks

class LoginList(ListView):
		model = Persona
		context_object_name = 'persona'
		template_name='login.html'

# def index(request):
# 	return render(request ,'login.html')

def noti(request):
	if request.method == 'POST':
		form = FormPersona(request.POST, request.FILES)
		# formC = FormComment(request.POST)

		# if formC.is_valid():
		# 	comment = formC.cleaned_data['comment']
		# 	userI = request.user.username
		# 	userI = str(userI)
		# 	print userI

		# 	commentM = Comment(persona=request.user, text=comment, ref_persona=nombre)
		# 	# commentM.ref_persona = str(request.user.username)
 		# 	# commentM.save()
		# 	# if commentM.text != '':
  
		# 	print comment
		# 	# return HttpResponse({comment:comment},content_type='json')
			
		# 	return JsonResponse({'comment':comment, 'user':userI})

		if form.is_valid():
			name = form.cleaned_data['nombre']
			email = form.cleaned_data['correo']
			edad = form.cleaned_data['edad']
			img = form.cleaned_data['image']
			noti = Persona(nombre=name, correo=email, edad=edad, image=img or None)

			noti.save()

	personas = Persona.objects.all().order_by('-id')
	comments = Comment.objects.all().order_by('-id')
	form = FormPersona()

	data = {
		'personas':personas,
		'comments':comments,
		'form': form,
	}

	return render(request ,'noti.html', data)

def comments(request, persona_id):
	personaN = get_list_or_404(Persona, id=persona_id)
	personas = Persona.objects.get(id=persona_id)
	print personas

	comments = Comment.objects.filter(ref_persona=personas).order_by('-id')
	print comments

	if request.method == 'POST':
		formC = FormComment(request.POST)

		if formC.is_valid():
			comment = request.POST.get('comment')
			userI = request.user.username
			userI = str(userI)
			
			# print Persona.ref_persona.all()
			p = Persona.objects.get(id=persona_id)
			print p 

			commentM = Comment(persona=request.user, text=comment, ref_persona=p)
			commentM.save()
	
			print commentM
			# return JsonResponse({'comment':comment, 'user':userI})
			return redirect('/noti/#%s' % (persona_id))
  
	data = {
		'personas':personas, 
		'comments':comments,
		}

	return render(request, 'comment.html', data)

def vcall(request):
	return render(request ,'vcall.html')

def prefile(request):
	return render(request ,'profile.html')

def register(request):
	return render(request ,'register.html')

def chat(request):
	return render(request ,'chat.html')

def helpme(request):
	return render(request, 'helpme.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<title>MyPaP tu red social</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
	{% block css %}
	{% endblock %}
</head>
<body>

	<nav class="deep-purple barra">
		<div class="nav-wrapper">
		<a href="/" class="brand-logo">MyPaP</a>
		<a href="#" data-activates="mobile-demo" class="button-collapse right">
			<i class="material-icons">menu</i>
		</a>
		<ul class="right hide-on-med-and-down">
			<li><a class="btn" href="{% url 'help' %}">Ayuda</a></li>
			<li><a href="{% url 'noti' %}">Nuevo</a></li>
			<li><a href="{% url 'vcall' %}">Videollamar</a></li>
			<li><a href="#">Chat</a></li>
			<li><a href="#">Amigos</a></li>
			<li><a class="dropdown-button" data-beloworigin="true" data-activates="dropdown2" href="{% url 'profile' %} ">
				{{request.user.username}}</a></li>
			<li><a href="#">Salir</a></li>
		</ul>

		<ul class="side-nav navm" id="mobile-demo">
			<li><a class="btn" href="{% url 'help' %}">Ayuda</a></li>
			<li><a class="btn green" href="#">Nuevo</a></li>
			<li><a class="btn red" href="#">Videollamar</a></li>
			<li><a class="btn orange" href="#">Chat</a></li>
			<li><a class="btn cyan" href="#">Amigos</a></li>
			<li><a class="btn blue" href="#">{{request.user.username}}</a></li>
			<li><a class="btn light-blue darken-4" href="#">Salir</a></li>
		</ul>

		<ul id='dropdown2' class='dropdown-content'>
			<li><a href="#!">one</a></li>
			<li class="divider"></li>
			<li><a href="#!">two</a></li>
			<li class="divider"></li>
			<li><a href="#!">three</a></li>
		</ul>
	</nav>

		<div class="row">

				<!--<div class="col s12 m8 l3 blue offset-m2 friends">-->

				<!--<ul class="collection">
				<li class="collection-item avatar">
				<img src="{% static 'img/html5.png' %}" alt="" class="circle">
				<span class="title">Fulano</span>

				<a href="{% url 'vcall' %}" class="right">
					<i class="material-icons">videocam</i>
				</a>
				<br>
				<a href="{% url 'chat' %}" class="right">
					<i class="material-icons">chat</i>
				</a>
			
				</li>
			</ul>

				<ul class="collection">
				<li class="collection-item avatar">
				<img src="{% static 'img/html5.png' %}" alt="" class="circle">
				<span class="title">Juan</span>
				
				<a href="{% url 'vcall' %}" class="right">
					<i class="material-icons">videocam</i>
				</a>
				<br>
				<a href="{% url 'chat' %}" class="right">
					<i class="material-icons">chat</i>
				</a>
			
				</li>
			</ul>

				<ul class="collection">
				<li class="collection-item avatar">
				<img src="{% static 'img/imgMyPaP.png' %}" alt="" class="circle">
				<span class="title">Jose</span>
				
				<a href="{% url 'vcall' %}" class="right">
					<i class="material-icons">videocam</i>
				</a>
				<br>
				<a href="{% url 'chat' %}" class="right">
					<i class="material-icons">chat</i>
				</a>

				</li>
			</ul>
			
			<div class="card-panel teal">
			<span class="white-text">I am a very simple card. 
				I am good at containing small bits of information.
			I am convenient because I require little markup to use
				effectively. I am similar to what is called a panel in other frameworks.
			</span>
			</div>-->
		
		<!--</div>-->
		
		<!--<div class="row">-->
			<!--<div class="col s12">-->
				{% block content %}{% endblock %}
			<!--</div>-->
		<!--</div>-->
		
	</div>

	<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
	<!--<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>-->
	<script src="{% static 'js/materialize.min.js' %}"></script>
	<script src="{% static 'js/navbar.js' %}"></script>
	{% block js %}{% endblock %}
</body>
</html>

templates/baseHome.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
	<title>MyPaP tu red social</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
</head>
<body class="deep-purple">

	<div class="container">
		<div class="row">
			{% block content %}
			{% endblock %}

		</div>
	</div>

	<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
	<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

templates/chat.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}

	<div class="container">
		<div class="row">
			<h3 class="center">hablando con {{request.user}}</h3>

			<div class="col s10 l6 offset-s1 offset-l3">
				<ul class="collection">
					<li class="collection-item">hola</li>
					<li class="collection-item">hola</li>
					<li class="collection-item">hola</li>
					<li class="collection-item">hola</li>
					<li class="collection-item">hola</li>
					<li class="collection-item">hola</li>
				</ul>
			</div>

			<div class="col s10 m8 l8 offset-s1 offset-m2 offset-l3">
				<form action="" method="post">
					{% csrf_token %}
					<div class="row">
						<div class="input-field col s8 l6">
							<label for="chat">Mensaje:</label>
							<input type="text" name="msj" id="chat">
						</div>
						<button class="col s4 l2 btn waves-effect waves-light">enviar</button>
					</div>
						<!--<input type="button" class="btn waves-effect waves-light" value="enviar">-->
				</form>
			</div>


		</div>
	</div>

{% endblock %}

templates/comment.html
{% comment %}
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
		
	{% block css %}
	{% endblock %}


{% endblock %}
{% endcomment %}
  <div class="container">
    <div class="row">
      
      <h1>{{personas}}</h1>

      {% for comment in comments %}
        <li>{{comment.persona}} - {{comment.text}}</li>
      {% endfor %}

    </div>
  </div>

templates/helpme.html
{% extends 'baseHome.html' %}

{% load staticfiles %}

{% block content %}

  <h3 class="white-text center animated bounceInLeft top-login">
    MyPaP es una red social, que te permite expresarte de cualquier forma.
  </h3>

  <h5 class="card-panel animated zoomIn">
    En la parte de arriba tienes una barra
    y tienes muchas opciones como: Nuevo, 
    Videollamar, Chatear, Amigos, tu nombre
    de usuario y Salir.
    <ol>
      <li><Strong>Nuevo</Strong>: es para subir fotos, hacer comentarios, compartir tus experiancias.</li>
      <li><Strong>Videollamar</Strong>: has videollamadas y habla con amigos, familia o conoce a más gente.</li>
      <li><Strong>Chatear</Strong>: Escribele a quien tu quieras.</li>
      <li><Strong>Amigos</Strong>: has solicitudes, mira cuantos seguidores tienes.</li>
      <li><Strong>Tu nombre de usuario</Strong>: aqui puedes ver tu foto de perfil o configurar tu cuenta.</li>
      <li><Strong>Salir</Strong>: salte de tu sesion</li>
    </ol>
  </h5>

  <h3 class="white-text center animated bounceInRight">
  {% if request.user.is_authenticated %}
    <a href="{% url 'index' %}">vuelve a tu Sesion</a>
  {% else %}
    Si ya saber como funciona MyPaP, te invitamas a que ingreses por aqui
    <a href="{% url 'index' %}">Iniciar Sesion</a> o 
    <a href="{% url 'register' %}">registrarte</a>. 
  {% endif %}
  </h3>

{% endblock %}

templates/login.html
{% extends 'baseHome.html' %}

{% load staticfiles %}

{% block content %}

	<h3 class="white-text center animated zoomIn">Estas en My<span id="keyword">P</span>aP</h3>

	<div class="white-text col s12 m12 l6 animated bounceInLeft">
	<h4 class="center">Con MyPaP puedes:</h4>
	
		<h5>
			<ol class="">
				<li>Hacer Videollamadas</li>
				<li>Conocer personas o nuevos amigos</li>
				<li>Subir fotos</li>
				<li>Chatear con tus amigos</li>
				<li>y otras cosas mas...</li>
			</ol>
		</h5>
	
		<h4 class="center"><a href="#user">Inicia Sesión</a> y verás....</h4>

		<h4 class=" center">Si quieres saber como funciona, da click en 
			<a href="{% url 'help' %}">ayuda</a>
		</h4>
	</div>

	<div id="login" class="col s12 m12 l6 center card-panel animated bounceInRight hoverable">
		<h4>Chatea, Videollama y disfruta con MyPaP</h4>
		{% csrf_token %}
		
		<div class="col s12">

		<form action="" method="GET">
			
			<div class="input-field ">
				<label for="user">Nombre de Usuario</label>
				<input type="text" name="username" id="user">
			</div>

			<div class="input-field"> 
				<label for="pw">Contraseña</label>
				<input type="password" name="password" id="pw">
			</div>
			
			<button class="btn blue" type="submit">acceder</button>
		</form>
		
		<h4>
			Si no tienes cuenta <a href="{% url 'register' %}">registrate</a>
		</h4>
		
		</div>

	</div>

{% endblock %}

templates/noti.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load cloudinary %}

{% comment %}
<!--{% load url from future %}-->
{% endcomment %}

{% block content %}
		
	{% block css %}
	<link rel="stylesheet" href="{% static 'css/noti.css' %}">
	{% endblock %}

		<div class="container">
			<div class="row">

				<div class="col s12 m8 l6 offset-l3 offset-m2 card-panel">
					<form action="" method="POST" class="center " enctype="multipart/form-data">
						{% csrf_token %}

						{% for field in form %}
							<p class="red-text">{{field.errors}}</p>
							{% if field.html_name == "nombre" %}
							<div class="input-field col s12">
								<label for="{{field.id_for_label}}">{{field.label}}</label>
								{{field}}	
							</div>
							{% elif field.html_name == "image" %}
							<div class="file-field input-field col s12">
								<div class="btn blue">
									<span>File</span>
									<input type="file" name="image">
								</div>
								<div class="file-path-wrapper">
									<input class="file-path validate" name="image" type="text" placeholder="Sube una">
								</div>
							</div>
							{% else %}
							<div class="input-field col s6">
								<label for="{{field.id_for_label}}">{{field.label}}</label>
								{{field}}
							</div>
							{% endif %}
						{% endfor %}

						{% comment %}
						{{ form.nombre.errors }}
						{% endcomment %}


						<!--<p class="red-text">error</p>-->

						<!--<div class="input-field col s12 l6">
							<label for="id_text">Nombre:</label>
							<input type="text" name="nombre" id="id_text" value="{{request.user}}">
						</div>
						
						<div class="input-field col s12 l6">
							<label for="id_email">Correo:</label>
							<input type="text" name="correo" id="id_email">
						</div>
						
						<div class="input-field col s12">
							<label for="id_edad">Edad:</label>
							<input type="number" name="edad" id="id_edad">
						</div>
						
						<div class="file-field input-field col s12">
							<div class="btn blue">
								<span>File</span>
								<input type="file" name="image">
							</div>
							<div class="file-path-wrapper">
								<input class="file-path validate" name="image" type="text" placeholder="Sube una">
							</div>
						</div>-->
						
						<!--<input type="submit" class="btn waves-effect waves-light" value="guardar">-->
						<button class="col s8 offset-s2 btn waves-effect waves-light orange" type="submit" name="action">
							Comentar
						</button>
						<div class="col s12">
							<h5> </h5>
						</div>
					</form>
			</div>

			{% for persona in personas %}
			<div class="col s12 m6 offset-m2 l6 offset-l3">
				<div class="card hoverable zoom">

					<div class="card-content">
						<div class="author">
							<!--<img src="{% static 'img/vaqueros.jpg' %}" class="" width="80">-->
						<div class="border" 
						style="background: url({% static 'img/vaqueros.jpg' %}); background-position: center; 
						background-size:cover">
							{% comment %}
							<img src="{% static 'img/vaqueros.jpg' %}" class="responsive-img">
							{% endcomment %}
						</div>
							<h4 class="center title">{{persona.nombre | title}}</h4>
						</div>
						<p>{{persona.correo}}</p>
					<p>{{persona.nombre}}</p>
					<p>{{request.user}}</p>
					</div>
					<div class="card-image responsive-img">
						
						{% comment %}
							{% cloudinary persona.image format="jpg" alt='Image' %}
						<img class="materialboxed" src="{{MEDIA_URL}}{{persona.image}}">
						{% if cloudinary %}
						{% else %}
						{% endif %}
						{% endcomment %}
					</div>
					<div class="card-action center">
						<a href="#" class="btn-flat"><i class="material-icons">grade</i></a>
						<a href="#" class="btn-flat" id="comment"><i class="material-icons">comment</i></a>
						{% if request.user.username == persona.nombre %}
						<a href="/noti/{{persona.id}}/" class="btn-flat"><i class="material-icons">delete</i></a>
						{% endif %}
					</div>
				</div>
			
				<form action="/comment/{{persona.id}}/" method="POST" class="formComment" id="form{{persona.id}}">
					{% csrf_token %}
					
					<ul class="collection">
						<div class="input-field col s8 m7 l8 animated slideInDown">
							<label for="id_comment">comentario</label>
							<input type="text" name="comment" id="id_comment">
						</div>
						<!--<br>-->
						<div class="input-field col s2 m5 l2 animated slideInDown" >
							<button class="btn col" type="submit" id="btn-form">comentar</button>
						</div>
					</ul>
				</form>

				<ul id="{{persona.id}}" class="col s12 collection animated slideInDown">
					{% for comment in comments %}
						{% if comment.ref_persona.id == persona.id %}
							<li class="collection-item"><strong>{{comment.persona}}</strong> {{comment.text}}</li>
						{% endif %}
					{% endfor %}
				</ul>

			</div>
			{% endfor %}

			</div>
		</div>

{% endblock %}

{% block js %}

		<script src="{% static 'js/noti.js' %}"></script>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">	
{% endblock %}	

{% block content %}
	<div class="row">
	<div class="col s12 m12 l10 offset-l1">

		<div id="vent" style="display:none;" class="card-panel col s12 center">
			<i id="close" class="material-icons right small">close</i>
			<h3>¿Quieres saber para que puede usar MyPaP? da click en
				<a href="{% url 'help'  %}"> ayuda</a>
			</h3>
		</div>

		<div class="card-panel col s12 m6 l6 animated flipInX">
			<img src="{% static 'img/imgMyPaP.png' %}" class="col s12"  alt="{{request.user.username}}">
			<a href="" class="btn">cambiar</a>
			<br><br>
		</div>

		<form method="POST" enctype="multipart/form-data" class="col s12 m6 l6 center card-panel animated flipInY">
		<h3 class="center">{{request.user.username}}</h3>
			{% csrf_token %}

			<div class="input-field">
				<label for="id_text">Nombre:</label>
				<input type="text" name="nombre" id="id_text" value="{{request.user.username}}">
			</div>
			
			<div class="input-field">
				<label for="id_email">Correo:</label>
				<input type="email" name="correo" id="id_email" value="{{request.user.email}}">
			</div>
			
			<!--<div class="input-field">
				<label for="id_pw">Contaseña:</label>
				<input type="password" name="pw" id="id_pw" value="{{request.user.password}}">
			</div>-->

			<div class="file-field input-field">
				<div class="btn">
				<span>Cambiar Foto</span>
				<input type="file" name="image" multiple>
			</div>
			<div class="file-path-wrapper">
				<input class="file-path validate" name="image" type="text" 
				placeholder="Upload one or more files">
			</div>
			</div>
			<!--<input type="submit" class="btn waves-effect waves-light" value="guardar">-->
			
			<button class="btn waves-effect waves-light blue" type="submit" name="action">Guardar</button>
			<h4>
				<a href="">Para cambiar la contraseña de click aquí</a>
			</h4>
		</form>

	</div>
	</div>

{% endblock content %}

{% block js %}

	<script src="{% static 'js/profile.js' %}"></script>	

{% endblock %}

templates/register.html
{% extends 'baseHome.html' %}

{% load staticfiles %}

{% block content %}

	<div class="white-text animated bounceInDown col s12 m12 l6 ">
		<h3 class="center">Al tener una cuenta en MyPaP podras:</h3>
		<h5>
			<ol>
				<li>Hacer Videollamadas a tus amigos</li>
				<li>Chatear con quien tú quieras</li>
				<li>Subir fotos comentar y compartir</li>
				<li>Seguir a tus amigos y obtener varios seguidores</li>
			</ol>
		</h5>
	</div>

	<div class="col s12 m12 l6 center card-panel hoverable animated bounceInUp">
		<!--<i class="material-icon right small">close</i>-->
		<h4>
			Si ya tienes una cuenta <br>
			<a href="{% url 'index' %}">Inicia Sesion</a><br>
		</h4>

		<h4 class="animated infinite pulse">Resgistrando...</h4>

		<form action="" method="get" class="">
			{% csrf_token %}
		
			<div class="input-field col s12">
				<label for="user">Nombre de Usuario</label>
				<input type="text" name="" id="user">
			</div>
			
			<div class="input-field col s6">
				<label for="first_name">Nombre</label>
				<input type="text" name="" id="first_name">
			</div>

			<div class="input-field col s6">
				<label for="last_name">Apellido</label>
				<input type="text" name="" id="last_name">
			</div>

			<div class="input-field col s12">
				<label for="email">Correo</label>
				<input type="email" name="" id="email">
			</div>

			<div class="input-field col s6">
				<label for="pw">Contraseña</label>
				<input type="password" name="pw2" id="pw">
			</div>

			<div class="input-field col s6">
				<label for="pw2">Contraseña</label>
				<input type="password" name="pw2" id="pw2">
			</div>

			<div class="file-field input-field col s12">
				<div class="btn blue">
				<span>Foto</span>
				<input type="file" name="image" multiple>
			</div>
			<div class="file-path-wrapper">
				<input class="file-path validate" name="image" type="text" 
				placeholder="Upload one or more files">
			</div>
			</div>

			<button class="btn green">registrar</button>
			<br><br>
		</form>
		
	</div>

{% endblock %}

templates/vcall.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

	<div class="col s12 m10 l5 center">
		<h4>{{request.user | title}}</h4>
		<img src="{% static 'img/imgMyPaP.png' %}" width="400" class="vcall" alt="">
		<button class="btn red waves-effect waves-light ">Llamar</button>
	</div>

	<div class="col s12 m10 l5 center">
		<h4>Juan</h4>
		<img src="{% static 'img/imgMyPaP.png' %}" width="580" class="vcall" alt="">
	</div>

{% endblock content %}